# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "SnapKit"
  pod 'CTMediator'
  pod 'ProgressHUD'
  pod 'IQKeyboardManager'
  
  pod 'GoogleWebRTC'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  
  pod 'CryptoSwift', '~> 1.8.0'
  
  pod 'CocoaAsyncSocket'
  pod 'Starscream'
end
